version: '3.3'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning /etc/redis/redis.conf
    volumes: 
      - cache:/data
      - ./redis.conf:/etc/redis/redis.conf
volumes:
  cache:
    driver: local